---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-account-agora-postgresql-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agora-postgresql-operator
subjects:
- kind: ServiceAccount
  name: agora-postgresql-operator
