apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default/

patchesStrategicMerge:
- manager-target.yaml

images:
- name: postgres-operator
  newName: perconalab/agora-postgresql-operator
  newTag: main
