apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../crd
- ../rbac/cluster
- ../manager/cluster

images:
- name: postgres-operator
  newName: ssk1994/agora-postgresql-operator
  newTag: main
