apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../crd
- ../rbac/namespace
- ../manager/namespace
images:
- name: postgres-operator
  newName: ssk1994/agora-postgresql-operator
  newTag: main
